// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// nipals
Rcpp::List nipals(Rcpp::NumericMatrix Xr, Rcpp::NumericMatrix Yr);
RcppExport SEXP fscca_nipals(SEXP XrSEXP, SEXP YrSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Xr(XrSEXP );
        Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Yr(YrSEXP );
        Rcpp::List __result = nipals(Xr, Yr);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// sparse_nipals
Rcpp::List sparse_nipals(Rcpp::NumericMatrix Xr, Rcpp::NumericMatrix Yr, double lamx, double lamy);
RcppExport SEXP fscca_sparse_nipals(SEXP XrSEXP, SEXP YrSEXP, SEXP lamxSEXP, SEXP lamySEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Xr(XrSEXP );
        Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Yr(YrSEXP );
        Rcpp::traits::input_parameter< double >::type lamx(lamxSEXP );
        Rcpp::traits::input_parameter< double >::type lamy(lamySEXP );
        Rcpp::List __result = sparse_nipals(Xr, Yr, lamx, lamy);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
