# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib fscca
NULL

#' NIPALS CCA algorithm
#'
#' @param x a matrix x that has been centered and scaled
#' @param y a matrix y that has been centered and scaled
#' @return a list containing a1 and b1
#' @export
nipals <- function(Xr, Yr) {
    .Call('fscca_nipals', PACKAGE = 'fscca', Xr, Yr)
}

#' Sparse NIPALS CCA algorithm
#'
#' @param x a matrix x that has been centered and scaled
#' @param y a matrix y that has been centered and scaled
#' @param lamx a positive enalty on 'a'
#' @param lamy a positive penalty on 'b'
#' @return a list containing a1 and b1
#' @export
sparse_nipals <- function(Xr, Yr, lamx, lamy) {
    .Call('fscca_sparse_nipals', PACKAGE = 'fscca', Xr, Yr, lamx, lamy)
}

