# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Hello world
#'
#' @return a list with foo bar
rcpp_hello_world <- function() {
    .Call('sccaf_rcpp_hello_world', PACKAGE = 'sccaf')
}

