# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib sccaf
NULL

#' Hello world
#'
#' @return a list with foo bar
#' @export
rcpp_hello_world <- function() {
    .Call('sccaf_rcpp_hello_world', PACKAGE = 'sccaf')
}

#' First column
#'
#' @param x a matrix
#' @return the first column of the matrix
#' @export
firstColumn <- function(nm, c) {
    .Call('sccaf_firstColumn', PACKAGE = 'sccaf', nm, c)
}

